export enum EnvVars {
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRS_DB = 'POSTGRS_DB',
  JWT_SECRET = 'JWT_SECRET',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  MAILTRAPIO_USER = 'MAILTRAPIO_USER',
  MAILTRAPIO_PASSWORD = 'MAILTRAPIO_PASSWORD',
}
